#!/usr/bin/env bash
echo "== list objects"

if [ -z "$1" ]; then
    echo "No bucket name provided, needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1


#we can do multi line with the \ character
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME