#!/usr/bin/env bash
echo "== sync"
set -e

if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1

#check for filename prefix
if [ -z "$2" ]; then
    echo "No filename prefix provided"
    exit 1
fi

FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY