version=0.1
[default.package.parameters]
s3_bucket = "my-lambda-artifacts-ab-1298"
region = "ap-southeast-2"
image_repository="946129064833.dkr.ecr.ap-southeast-2.amazonaws.com/python-container-example"
[default.deploy.parameters]
s3_bucket = "my-lambda-artifacts-ab-1298"
region = "ap-southeast-2"
image_repository="946129064833.dkr.ecr.ap-southeast-2.amazonaws.com/python-container-example"