version=0.1
[default.package.parameters]
s3_bucket = "my-lambda-artifacts-ab-1298"
region = "ap-southeast-2"
[default.deploy.parameters]
s3_bucket = "my-lambda-artifacts-ab-1298"
region = "ap-southeast-2"